version: '3'

services:
  orders-db:
    container_name: melp_restaurants
    image: postgres:14.3
    restart: always
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=P@ssword
      - POSTGRES_DB=melpdb
